//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinStat.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Presentation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Presentation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinStat.Resources.Presentation", typeof(Presentation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string ActivityIndicatorCaptionText {
            get {
                return ResourceManager.GetString("ActivityIndicatorCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinStat.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMEX.
        /// </summary>
        public static string Exchange_Amex {
            get {
                return ResourceManager.GetString("Exchange_Amex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity.
        /// </summary>
        public static string Exchange_Commodity {
            get {
                return ResourceManager.GetString("Exchange_Commodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto.
        /// </summary>
        public static string Exchange_Crypto {
            get {
                return ResourceManager.GetString("Exchange_Crypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETF.
        /// </summary>
        public static string Exchange_Etf {
            get {
                return ResourceManager.GetString("Exchange_Etf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euronext.
        /// </summary>
        public static string Exchange_Euronext {
            get {
                return ResourceManager.GetString("Exchange_Euronext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forex.
        /// </summary>
        public static string Exchange_Forex {
            get {
                return ResourceManager.GetString("Exchange_Forex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Exchange_Index {
            get {
                return ResourceManager.GetString("Exchange_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSE.
        /// </summary>
        public static string Exchange_Lse {
            get {
                return ResourceManager.GetString("Exchange_Lse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutual Fund.
        /// </summary>
        public static string Exchange_MutualFund {
            get {
                return ResourceManager.GetString("Exchange_MutualFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASDAQ.
        /// </summary>
        public static string Exchange_Nasdaq {
            get {
                return ResourceManager.GetString("Exchange_Nasdaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSE.
        /// </summary>
        public static string Exchange_Nse {
            get {
                return ResourceManager.GetString("Exchange_Nse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NYSE.
        /// </summary>
        public static string Exchange_Nyse {
            get {
                return ResourceManager.GetString("Exchange_Nyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSX.
        /// </summary>
        public static string Exchange_Tsx {
            get {
                return ResourceManager.GetString("Exchange_Tsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xetra.
        /// </summary>
        public static string Exchange_Xetra {
            get {
                return ResourceManager.GetString("Exchange_Xetra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something bad happened. Please try it later or contact us..
        /// </summary>
        public static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don’t have permission to access this page..
        /// </summary>
        public static string NoAccessToPage {
            get {
                return ResourceManager.GetString("NoAccessToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available data.
        /// </summary>
        public static string NoAvailableData {
            get {
                return ResourceManager.GetString("NoAvailableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems you are offline. Please check your internet connection..
        /// </summary>
        public static string OfflineErrorMessage {
            get {
                return ResourceManager.GetString("OfflineErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string SearchBarPlaceholder {
            get {
                return ResourceManager.GetString("SearchBarPlaceholder", resourceCulture);
            }
        }
    }
}
